//****************************************//
//*                                      *//
//* This code is generated by parseidon. *//
//*     https://github.com/parseidon     *//
//*                                      *//
//****************************************//

using System.Text.RegularExpressions;

namespace Parseidon.Parser;

public class ParseidonParser
{
    public class Visitor
    {
        public virtual void OnCSIdentifier(ParseidonParser.ASTNode node) {}
        public virtual void OnClassName(ParseidonParser.ASTNode node) {}
        public virtual void OnDefinition(ParseidonParser.ASTNode node) {}
        public virtual void OnDot(ParseidonParser.ASTNode node) {}
        public virtual void OnDrop(ParseidonParser.ASTNode node) {}
        public virtual void OnExpression(ParseidonParser.ASTNode node) {}
        public virtual void OnGrammar(ParseidonParser.ASTNode node) {}
        public virtual void OnIdentifier(ParseidonParser.ASTNode node) {}
        public virtual void OnIsTerminal(ParseidonParser.ASTNode node) {}
        public virtual void OnLiteral(ParseidonParser.ASTNode node) {}
        public virtual void OnNamespace(ParseidonParser.ASTNode node) {}
        public virtual void OnOneOrMore(ParseidonParser.ASTNode node) {}
        public virtual void OnOptional(ParseidonParser.ASTNode node) {}
        public virtual void OnPrefix(ParseidonParser.ASTNode node) {}
        public virtual void OnPrimary(ParseidonParser.ASTNode node) {}
        public virtual void OnRegex(ParseidonParser.ASTNode node) {}
        public virtual void OnSequence(ParseidonParser.ASTNode node) {}
        public virtual void OnSuffix(ParseidonParser.ASTNode node) {}
        public virtual void OnZeroOrMore(ParseidonParser.ASTNode node) {}
    
        public virtual void Visit(ASTNode node)
        {
            if(node == null)
                return;
            foreach(ASTNode child in node.Children)
                Visit(child);
            CallEvent(node.TokenId, node);
        }
    
        public virtual void CallEvent(Int32 tokenId, ASTNode node)
        {
            switch(tokenId)
            {
                case 21: OnCSIdentifier(node); break;
                case 31: OnClassName(node); break;
                case 30: OnDefinition(node); break;
                case 7: OnDot(node); break;
                case 12: OnDrop(node); break;
                case 29: OnExpression(node); break;
                case 34: OnGrammar(node); break;
                case 24: OnIdentifier(node); break;
                case 11: OnIsTerminal(node); break;
                case 19: OnLiteral(node); break;
                case 32: OnNamespace(node); break;
                case 13: OnOneOrMore(node); break;
                case 15: OnOptional(node); break;
                case 27: OnPrefix(node); break;
                case 25: OnPrimary(node); break;
                case 17: OnRegex(node); break;
                case 28: OnSequence(node); break;
                case 26: OnSuffix(node); break;
                case 14: OnZeroOrMore(node); break;
            }
        }
    }

    public void Parse(String text)
    {
        ParserState state = new ParserState(text);
        ASTNode actualNode = new ASTNode(-1, "ROOT", "");            
        if(CheckRule_Grammar(actualNode, state))
            rootNode = actualNode;
    }

    public void Visit(Visitor visitor)
    {
        if(rootNode == null)
            throw new Exception("Root node is null");
        visitor.Visit(rootNode);
    }
    
    public class ASTNode
    {
        private List<ASTNode> _children { get; } = new List<ASTNode>();
        private ASTNode? _parent = null;
    
        public String Text { get; set; }
        public String Name { get; set; }
        public IReadOnlyList<ASTNode> Children { get => _children; } 
        public Int32 TokenId { get; private set; }
        public Int32 Position { get; set; }
        public ASTNode? Parent { get => _parent; }            
    
        internal ASTNode(Int32 tokenId, String name, String text)
        {
            Text = text;
            TokenId = tokenId;
            Name = name;
        }
    
        internal void AssignFrom(ASTNode node)
        {
            Int32 nodeIndex = _children.IndexOf(node);
            if (nodeIndex >= 0)
            {
                Text = node.Text;
                TokenId = node.TokenId;
                Position = node.Position;
                List<ASTNode> tempChildren = new List<ASTNode>(node.Children);
                foreach(ASTNode child in tempChildren)
                {
                    child.SetParent(this, nodeIndex);
                    nodeIndex++;
                }
                _children.Remove(node);
            }
        }
         
        internal String GetText()
        {
            if (Children.Count > 0)
                return String.Join("", Children.Select(x => x.GetText()));
            else
                return Text;
        }
    
        internal void SetParent(ASTNode? parent, Int32 index = -1)
        {
            if(_parent != null)
                _parent._children.Remove(this);
            _parent = parent;
            if(_parent != null)
            {
                if(index < 0)
                    _parent._children.Add(this);
                else
                    _parent._children.Insert(index, this);
            }
        }
        
        internal void AddChild(ASTNode? child)
        {
            if(child != null)
                _children.Add(child);
        }
    
        internal void ClearChildren()
        {
            _children.Clear();
        }            
    }
    
    private class ParserState
    {
        public ParserState(String text)
        {
            Text = text;
        }            
        public String Text { get; }
        public Int32 Position { get; internal set; } = 0;
        public Boolean Eof => !(Position < Text.Length);
    }
    
    private ASTNode? rootNode = null;
    
    private Boolean CheckRegEx(ASTNode parentNode, ParserState state, String regEx)
    {
        Int32 oldPosition = state.Position;
        if((state.Position < state.Text.Length) && Regex.Match(state.Text[state.Position].ToString(), regEx).Success)
        {
            state.Position++;
            parentNode.AddChild(new ASTNode(-1, "REGEX", state.Text.Substring(oldPosition, state.Position - oldPosition)));
            return true;
        }
        state.Position = oldPosition;
        return false;
    }
    
    private Boolean CheckText(ASTNode parentNode, ParserState state, String text)
    {
        Int32 oldPosition = state.Position;
        Int32 position = 0;
        while (position < text.Length)
        {
            if(state.Eof || (state.Text[state.Position] != text[position]))
            {
                state.Position = oldPosition;
                return false;
            }
            position++;
            state.Position++;
        }
        parentNode.AddChild(new ASTNode(-1, "TEXT", state.Text.Substring(oldPosition, state.Position - oldPosition)));
        return true;
    }
    
    private Boolean CheckAnd(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> leftCheck, Func<ASTNode, Boolean> rightCheck)
    {
        Int32 oldPosition = state.Position;
        ASTNode tempNode = new ASTNode(parentNode.TokenId, "AND", parentNode.Text);
        tempNode.Position = parentNode.Position;
        if(leftCheck(tempNode))
        {
            if(rightCheck(tempNode))
            {
                parentNode.AddChild(tempNode);
                parentNode.AssignFrom(tempNode);
                return true;
            }
        }
        state.Position = oldPosition;
        return false;
    }
    
    private Boolean CheckOr(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> leftCheck, Func<ASTNode, Boolean> rightCheck)
    {
        Int32 oldPosition = state.Position;
        if(leftCheck(parentNode))
            return true;
        if(rightCheck(parentNode))
            return true;
        state.Position = oldPosition;
        return false;
    }
    
    private Boolean Drop(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> check)
    {
        Int32 oldPosition = state.Position;
        ASTNode tempNode = new ASTNode(-1, "", "");
        return check(tempNode);
    }
    
    private Boolean CheckOneOrMore(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> check)
    {
        Int32 oldPosition = state.Position;
        if(check(parentNode))
        {
            oldPosition = state.Position;
            while(check(parentNode))
            {
                oldPosition = state.Position;
            }
            state.Position = oldPosition;
            return true;
        }
        state.Position = oldPosition;
        return false;
    }
    
    private Boolean CheckZeroOrMore(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> check)
    {
        Int32 oldPosition = state.Position;
        while((!state.Eof) && check(parentNode))
        {
            oldPosition = state.Position;
        }
        state.Position = oldPosition;
        return true;
    }
    
    private Boolean CheckDifference(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> leftCheck, Func<ASTNode, Boolean> rightCheck)
    {
        Int32 oldPosition = state.Position;
        if(leftCheck(parentNode))
        {
            state.Position = oldPosition;
            if(rightCheck(parentNode))
                return true;
        }
        state.Position = oldPosition;
        return false;
    }
    
    private Boolean CheckRange(ASTNode parentNode, ParserState state, Int32 minCount, Int32 maxCount, Func<ASTNode, Boolean> check)
    {
        Int32 oldPosition = state.Position;
        Int32 count = 0;
        while((count <= maxCount) && check(parentNode))
        {
            oldPosition = state.Position;
            count++;
        }
        if(count >= minCount)
            return true;
        state.Position = oldPosition;
        return true;
    }
    
    private Boolean MakeTerminal(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> check)
    {
        Int32 oldPosition = state.Position;
        ASTNode tempNode = new ASTNode(-1, "", "");
        Boolean result =  check(tempNode);
        if (result)
        {
            tempNode.Text = tempNode.GetText();
            tempNode.ClearChildren();
            parentNode.Text = tempNode.GetText();
        }
        return result;
    }
    
    private Boolean PromoteAction(ASTNode parentNode, ParserState state, Func<ASTNode, Boolean> check)
    {
        Int32 childCount = parentNode.Children.Count;
        Boolean result = check(parentNode);
        if(result && (childCount < parentNode.Children.Count))
        {
            ASTNode newNode = parentNode.Children.Last();
            parentNode.AssignFrom(newNode);
        }
        return result;
    }
    
    private Boolean AddVirtualNode(ASTNode parentNode, ParserState state, Int32 tokenId, String text)
    {
        parentNode.AddChild(new ASTNode(tokenId, "VIRTUAL", text));
        return true;
    }

    private Boolean CheckRule_BracketClose(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(0, "BracketClose", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, ")"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_BracketOpen(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(1, "BracketOpen", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "("),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_CSIdentCont(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(20, "CSIdentCont", "");
        Boolean result =         
            CheckZeroOrMore(actualNode, state, 
                (actualNode) => CheckRegEx(actualNode, state, "[a-zA-Z0-9_.]")
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_CSIdentifier(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(21, "CSIdentifier", "");
        Boolean result =         
            MakeTerminal(actualNode, state, 
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckRule_IdentStart(actualNode, state),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_CSIdentCont(actualNode, state),
                        (actualNode) => CheckRule_Spacing(actualNode, state)
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Char(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(18, "Char", "");
        Boolean result =         
            CheckOr(actualNode, state, 
                (actualNode) => CheckRegEx(actualNode, state, "[^'\\\\]"),
                (actualNode) => CheckOr(actualNode, state, 
                    (actualNode) => CheckText(actualNode, state, "\\'"),
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckText(actualNode, state, "\\\\"),
                        (actualNode) => CheckRule_EscapeChars(actualNode, state)
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_ClassName(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(31, "ClassName", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Spacing(actualNode, state),
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => Drop(actualNode, state, 
                        (actualNode) => CheckText(actualNode, state, "@class")
                    ),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_Spacing(actualNode, state),
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => CheckRule_CSIdentifier(actualNode, state),
                            (actualNode) => CheckRule_LineEnd(actualNode, state)
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Comment(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(2, "Comment", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "#"),
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckZeroOrMore(actualNode, state, 
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => Drop(actualNode, state, 
                                (actualNode) => CheckRegEx(actualNode, state, "[\\r\\n]")
                            ),
                            (actualNode) => CheckRegEx(actualNode, state, ".")
                        )
                    ),
                    (actualNode) => CheckRegEx(actualNode, state, "[\\r\\n]")
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Config(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(33, "Config", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Namespace(actualNode, state),
                (actualNode) => CheckRule_ClassName(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Definition(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(30, "Definition", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Spacing(actualNode, state),
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckRange(actualNode, state, 0, 1,
                        (actualNode) => CheckOr(actualNode, state, 
                            (actualNode) => CheckRule_IsTerminal(actualNode, state),
                            (actualNode) => CheckRule_Drop(actualNode, state)
                        )
                    ),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_Identifier(actualNode, state),
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => Drop(actualNode, state, 
                                (actualNode) => CheckRule_Equal(actualNode, state)
                            ),
                            (actualNode) => CheckAnd(actualNode, state, 
                                (actualNode) => CheckRule_Expression(actualNode, state),
                                (actualNode) => CheckRule_LineEnd(actualNode, state)
                            )
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Dot(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(7, "Dot", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "."),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Drop(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(12, "Drop", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "!"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Equal(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(9, "Equal", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "="),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_EscapeChars(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(10, "EscapeChars", "");
        Boolean result =         
            CheckOr(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "\\0"),
                (actualNode) => CheckOr(actualNode, state, 
                    (actualNode) => CheckText(actualNode, state, "\\a"),
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckText(actualNode, state, "\\b"),
                        (actualNode) => CheckOr(actualNode, state, 
                            (actualNode) => CheckText(actualNode, state, "\\f"),
                            (actualNode) => CheckOr(actualNode, state, 
                                (actualNode) => CheckText(actualNode, state, "\\n"),
                                (actualNode) => CheckOr(actualNode, state, 
                                    (actualNode) => CheckText(actualNode, state, "\\r"),
                                    (actualNode) => CheckOr(actualNode, state, 
                                        (actualNode) => CheckText(actualNode, state, "\\t"),
                                        (actualNode) => CheckOr(actualNode, state, 
                                            (actualNode) => CheckText(actualNode, state, "\\v"),
                                            (actualNode) => CheckOr(actualNode, state, 
                                                (actualNode) => CheckAnd(actualNode, state, 
                                                    (actualNode) => CheckText(actualNode, state, "\\u"),
                                                    (actualNode) => CheckRegEx(actualNode, state, "[0-9a-fA-F]{4}")
                                                ),
                                                (actualNode) => CheckAnd(actualNode, state, 
                                                    (actualNode) => CheckText(actualNode, state, "\\u"),
                                                    (actualNode) => CheckRegEx(actualNode, state, "[0-9a-fA-F]{8}")
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Expression(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(29, "Expression", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Sequence(actualNode, state),
                (actualNode) => CheckZeroOrMore(actualNode, state, 
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_Or(actualNode, state),
                        (actualNode) => CheckRule_Sequence(actualNode, state)
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Grammar(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(34, "Grammar", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Config(actualNode, state),
                (actualNode) => CheckOneOrMore(actualNode, state, 
                    (actualNode) => CheckRule_Definition(actualNode, state)
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_IdentCont(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(22, "IdentCont", "");
        Boolean result =         
            CheckZeroOrMore(actualNode, state, 
                (actualNode) => CheckRegEx(actualNode, state, "[a-zA-Z0-9_]")
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_IdentStart(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(23, "IdentStart", "");
        Boolean result =         CheckRegEx(actualNode, state, "[a-zA-Z_]");
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Identifier(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(24, "Identifier", "");
        Boolean result =         
            MakeTerminal(actualNode, state, 
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckRule_IdentStart(actualNode, state),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_IdentCont(actualNode, state),
                        (actualNode) => CheckRule_Spacing(actualNode, state)
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_IsTerminal(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(11, "IsTerminal", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "$"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_LineEnd(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(8, "LineEnd", "");
        Boolean result =         
            Drop(actualNode, state, 
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckRule_Spacing(actualNode, state),
                    (actualNode) => CheckText(actualNode, state, ";")
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Literal(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(19, "Literal", "");
        Boolean result =         
            MakeTerminal(actualNode, state, 
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => Drop(actualNode, state, 
                                (actualNode) => CheckText(actualNode, state, "'")
                            ),
                            (actualNode) => CheckAnd(actualNode, state, 
                                (actualNode) => CheckZeroOrMore(actualNode, state, 
                                    (actualNode) => CheckRule_Char(actualNode, state)
                                ),
                                (actualNode) => Drop(actualNode, state, 
                                    (actualNode) => CheckText(actualNode, state, "'")
                                )
                            )
                        ),
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => CheckText(actualNode, state, "\""),
                            (actualNode) => CheckAnd(actualNode, state, 
                                (actualNode) => CheckZeroOrMore(actualNode, state, 
                                    (actualNode) => CheckRule_Char(actualNode, state)
                                ),
                                (actualNode) => CheckText(actualNode, state, "\"")
                            )
                        )
                    ),
                    (actualNode) => CheckRule_Spacing(actualNode, state)
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Namespace(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(32, "Namespace", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Spacing(actualNode, state),
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => Drop(actualNode, state, 
                        (actualNode) => CheckText(actualNode, state, "@namespace")
                    ),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckRule_Spacing(actualNode, state),
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => CheckRule_CSIdentifier(actualNode, state),
                            (actualNode) => CheckRule_LineEnd(actualNode, state)
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_NewLine(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(4, "NewLine", "");
        Boolean result =         CheckRegEx(actualNode, state, "[\\r]");
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Number(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(3, "Number", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRegEx(actualNode, state, "[1-9]"),
                (actualNode) => CheckZeroOrMore(actualNode, state, 
                    (actualNode) => CheckRegEx(actualNode, state, "[0-9]")
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_OneOrMore(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(13, "OneOrMore", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "+"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Optional(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(15, "Optional", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "?"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Or(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(16, "Or", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "/"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Prefix(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(27, "Prefix", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRange(actualNode, state, 0, 1,
                    (actualNode) => CheckRule_Drop(actualNode, state)
                ),
                (actualNode) => CheckRule_Suffix(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Primary(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(25, "Primary", "");
        Boolean result =         
            CheckOr(actualNode, state, 
                (actualNode) => CheckRule_Identifier(actualNode, state),
                (actualNode) => CheckOr(actualNode, state, 
                    (actualNode) => CheckRule_Literal(actualNode, state),
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => Drop(actualNode, state, 
                                (actualNode) => CheckRule_BracketOpen(actualNode, state)
                            ),
                            (actualNode) => CheckAnd(actualNode, state, 
                                (actualNode) => CheckRule_Expression(actualNode, state),
                                (actualNode) => Drop(actualNode, state, 
                                    (actualNode) => CheckRule_BracketClose(actualNode, state)
                                )
                            )
                        ),
                        (actualNode) => CheckOr(actualNode, state, 
                            (actualNode) => CheckRule_Regex(actualNode, state),
                            (actualNode) => CheckRule_Dot(actualNode, state)
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Regex(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(17, "Regex", "");
        Boolean result =         
            MakeTerminal(actualNode, state, 
                (actualNode) => CheckAnd(actualNode, state, 
                    (actualNode) => CheckText(actualNode, state, "["),
                    (actualNode) => CheckAnd(actualNode, state, 
                        (actualNode) => CheckOneOrMore(actualNode, state, 
                            (actualNode) => CheckOr(actualNode, state, 
                                (actualNode) => CheckRegEx(actualNode, state, "[^\\\\\\[\\]]"),
                                (actualNode) => CheckOr(actualNode, state, 
                                    (actualNode) => CheckText(actualNode, state, "\\["),
                                    (actualNode) => CheckOr(actualNode, state, 
                                        (actualNode) => CheckText(actualNode, state, "\\]"),
                                        (actualNode) => CheckOr(actualNode, state, 
                                            (actualNode) => CheckText(actualNode, state, "\\-"),
                                            (actualNode) => CheckOr(actualNode, state, 
                                                (actualNode) => CheckText(actualNode, state, "\\^"),
                                                (actualNode) => CheckOr(actualNode, state, 
                                                    (actualNode) => CheckText(actualNode, state, "\\\\"),
                                                    (actualNode) => CheckRule_EscapeChars(actualNode, state)
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        ),
                        (actualNode) => CheckAnd(actualNode, state, 
                            (actualNode) => CheckText(actualNode, state, "]"),
                            (actualNode) => CheckAnd(actualNode, state, 
                                (actualNode) => CheckRange(actualNode, state, 0, 1,
                                    (actualNode) => CheckAnd(actualNode, state, 
                                        (actualNode) => CheckText(actualNode, state, "{"),
                                        (actualNode) => CheckAnd(actualNode, state, 
                                            (actualNode) => CheckRule_Number(actualNode, state),
                                            (actualNode) => CheckText(actualNode, state, "}")
                                        )
                                    )
                                ),
                                (actualNode) => CheckRule_Spacing(actualNode, state)
                            )
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Sequence(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(28, "Sequence", "");
        Boolean result =         
            CheckZeroOrMore(actualNode, state, 
                (actualNode) => CheckRule_Prefix(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Spacing(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(6, "Spacing", "");
        Boolean result =         
            Drop(actualNode, state, 
                (actualNode) => CheckZeroOrMore(actualNode, state, 
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckRule_NewLine(actualNode, state),
                        (actualNode) => CheckOr(actualNode, state, 
                            (actualNode) => CheckRule_WhiteSpace(actualNode, state),
                            (actualNode) => CheckRule_Comment(actualNode, state)
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_Suffix(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(26, "Suffix", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckRule_Primary(actualNode, state),
                (actualNode) => CheckRange(actualNode, state, 0, 1,
                    (actualNode) => CheckOr(actualNode, state, 
                        (actualNode) => CheckRule_Optional(actualNode, state),
                        (actualNode) => CheckOr(actualNode, state, 
                            (actualNode) => CheckRule_ZeroOrMore(actualNode, state),
                            (actualNode) => CheckRule_OneOrMore(actualNode, state)
                        )
                    )
                )
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_WhiteSpace(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(5, "WhiteSpace", "");
        Boolean result =         CheckRegEx(actualNode, state, "[ \\t\\r\\n]");
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
    private Boolean CheckRule_ZeroOrMore(ASTNode parentNode, ParserState state)
    {
        Int32 oldPosition = state.Position;
        ASTNode actualNode = new ASTNode(14, "ZeroOrMore", "");
        Boolean result =         
            CheckAnd(actualNode, state, 
                (actualNode) => CheckText(actualNode, state, "*"),
                (actualNode) => CheckRule_Spacing(actualNode, state)
            );
        Int32 foundPosition = state.Position;
        if(result && ((actualNode.Children.Count > 0) || (actualNode.Text != "")))
            parentNode.AddChild(actualNode);
        return result;
    }
}